name: Build and Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        target: [
            native,
            x86_64-linux-gnu,
            x86_64-linux-musl,
            x86_64-windows,
            aarch64-macos,
            aarch64-linux-gnu,
            aarch64-linux-musl,
            # TODO: bsd
          ]
        optimize: [Debug, ReleaseSafe, ReleaseFast, ReleaseSmall]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.15.1

      - name: Build
        run: zig build -Dtarget=${{ matrix.target }} -Doptimize=${{ matrix.optimize }}
