name: Build and Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        target: [
          native,
          native-linux-gnu,
          native-linux-musl,
          native-windows,
          # TODO: bsd
        ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.16.0

      - name: Build
        run: zig build samples -Dtarget=${{ matrix.target }}
